### ISSUE TITLE
Links to About and Getting Started broken in Readme

### ISSUE THREAD

**Issue by wolewnicki** [parallelvirtualcluster/pvc#2]
The about link in the readme is `https://docs.parallelvirtualcluster.org/en/latest/about/`, I believe the correct link is `https://docs.parallelvirtualcluster.org/en/latest/about-pvc/`. The link for Getting started, in the readme is `https://docs.parallelvirtualcluster.org/en/latest/getting-started/` and I think the correct link is `https://docs.parallelvirtualcluster.org/en/latest/deployment/getting-started/`

**Comment by joshuaboniface** [comment]
Thanks for reporting! I had noticed these a while back but hadn't gotten around to fixing them. The updated README as of tonight has the correct links!
